### ISSUE TITLE
Collecting location information from the user on the project addition screen.

### ISSUE THREAD

**Issue by mustyilmaz** [CankayaUniversity/ceng-407-408-2023-2024-AGRICROWD-Tarimda-Kitlesel-Fonlama-Uygulamasi#20]
- [x] If the admin specifies that location information is required for a particular project category, then when the user selects that specific project category on the project addition screen, the location information should be collected from the user. Subsequently, on the project detail page, the project location should be visible to users who wish to invest/donate.

- At the bottom of the basicInfo component linked to the addProject component, if a category requiring location information is selected, a message appears indicating that the requiresLocation flag will be set to True and location information will be obtained as if. You should remove this message and make the necessary changes here to ensure the process is completed.

**Comment by gklemr** [comment]
Done
