### ISSUE TITLE
Preparing the frontend designs for the latest components.

### ISSUE THREAD

**Issue by mustyilmaz** [CankayaUniversity/ceng-407-408-2023-2024-AGRICROWD-Tarimda-Kitlesel-Fonlama-Uygulamasi#21]
The frontend designs of the following components need to be designed and adapted: 

- [x] Admin and its sub-components,
- [x] User Panel and its sub-components,
- [x] Add Project and its sub-components.

**Comment by mustyilmaz** [comment]
First, you should pull the latest code to your local machine.

**Comment by mustyilmaz** [comment]
Although the components in the admin panel do not change, updates must be made accordingly since the route mechanism has been added to the admin panel.

**Comment by mustyilmaz** [comment]
In the last code merge process, new component(s) were added to the add project component.

**Comment by mustyilmaz** [comment]
The designs of the remaining navbars of the components need to be created urgently.

**Comment by erenburuk** [comment]
Tasks done.
