### ISSUE TITLE
Splitting the user panel into tabs and adding a few components.

### ISSUE THREAD

**Issue by mustyilmaz** [CankayaUniversity/ceng-407-408-2023-2024-AGRICROWD-Tarimda-Kitlesel-Fonlama-Uygulamasi#22]
- [x] The user panel should be divided into tabs to enhance the user experience. Users should initially encounter the main user panel component displaying "Hello....", and then they should be able to switch between tabs to: 
- [x] view and update their personal information (already available), 
- [x] change their password, 
- [x] and also access the "My Projects" tab.

- [x] Users should be able to change their passwords, and necessary validations should be added.
- [x] Users should be able to observe the status of their submitted projects in the "My Projects" section (Approved, along with a message stating the reason if not approved).

**Comment by mustyilmaz** [comment]
I set up the foldering process. At the same time, the template of the route mechanism is ready.

**Comment by remzn** [comment]
I completed all .
