### ISSUE TITLE
The projects to be listed will be read from the database and listed on the client side, allowing users to observe project details.

### ISSUE THREAD

**Issue by mustyilmaz** [CankayaUniversity/ceng-407-408-2023-2024-AGRICROWD-Tarimda-Kitlesel-Fonlama-Uygulamasi#24]
- [x] Users should be able to view certain information about the projects listed in the main project table on the homepage or the projects route.
- [x] When clicked on the relevant project, all remaining information about the project should be displayed as expected, enabling users to perform investment/donation transactions by placing buttons accordingly.

**Comment by mustyilmaz** [comment]
- [ ] The /projects route should be created and the frontend and backend work of the base card component, which contains the basic information of the project (project name, images, etc.), should be carried out from start to finish.
- [ ] In the "/projects/:projectId/details" route, front-end and back-end designs should be provided so that users can access more detailed information about that project and interact with investment or donation buttons when clicking on the relevant card.

**Comment by gklemr** [comment]
Currently approved projects can be viewed

**Comment by mustyilmaz** [comment]
The component of the project detail page has been prepared, frontend work needs to be done. At the same time, functionality must be ensured by adding relevant buttons.

**Comment by adiltukenmez** [comment]
fund and donate buttons are added to the project details page

**Comment by mustyilmaz** [comment]
By adding the project owner information, the process of displaying detailed information about the project in general has been completed.
