### ISSUE TITLE
Functionality of Invest and Donation buttons on the detail page of the project

### ISSUE THREAD

**Issue by mustyilmaz** [CankayaUniversity/ceng-407-408-2023-2024-AGRICROWD-Tarimda-Kitlesel-Fonlama-Uygulamasi#31]
- [x] Users should be able to donate or invest in the project they interact with.
- [x] At this stage, the working mechanisms of these buttons need to be designed and communicate with smart contracts as they should.

**Comment by adiltukenmez** [comment]
Those buttons are implemented and ready to be added to the project.

**Comment by mustyilmaz** [comment]
The id of the relevant project is available in the added "Project Detail" component. With this information, all remaining operations must be completed urgently.

**Comment by adiltukenmez** [comment]
Fund and Donate buttons are implemented and added to our project.
