### ISSUE TITLE
Project Updates, Merging Process, and Other Important Considerations

### ISSUE THREAD

**Issue by mustyilmaz** [CankayaUniversity/ceng-407-408-2023-2024-AGRICROWD-Tarimda-Kitlesel-Fonlama-Uygulamasi#33]
# Project Updates, Merging Process, and Other Important Considerations

Before starting your work, it's important to review the latest changes and merge operations. This ensures we're all aligned and aware of any updates that may affect our tasks.

## Latest Changes:

1. **Code Updates:**
   - Review all code changes to identify any major updates or modifications.
### Most Important: 
2. **Summary of Merged Code:**
   - If you have successfully merged your code, you are responsible for summarizing it under this issue, even if you have mentioned the details of your code in the issues you worked on.

## Action Items:

1. **Communication:**
   - Keep the lines of communication open within the team. Ensure everyone is informed about the project's progress, especially concerning any significant updates or changes. Focus on the details to ensure everyone is well-informed.

2. **Review the code snippets you prepared yourself:**
   - Thoroughly review the code changes, focusing on your assigned tasks. If there are any major changes or uncertainties, reach out to the relevant team members for discuss.

3. **Folder Structure and Routing Mechanism:**
   - Double-check if you have made any changes to the folder structure or routing mechanisms. Changes in these areas can have a significant impact, so it is very important to be aware of them.

4. **Merge Operations:**
   - If you're confident that the code you've prepared is ready for merging and there are no major changes affecting it, go ahead with the merge operation. However, if you have any doubts or concerns, discuss them with the team to address any issues before proceeding.

## Additional Steps:

- Conduct a comprehensive review of the codebase and project status.
- Foster effective communication within the team, ensuring everyone is informed and engaged.
- Merge the code once everything is in order, following the established procedures and protocols.
- Encourage team members to share updates and progress on related issues, fostering a collaborative environment where everyone is involved and informed.

Remember, transparency and collaboration are key to the success of our project. If you have any questions or require assistance, don't hesitate to reach out to the team. Together, we can achieve our goals efficiently and effectively.

**Comment by mustyilmaz** [comment]
- By completing my latest [merge](https://github.com/CankayaUniversity/ceng-407-408-2023-2024-AGRICROWD-Tarimda-Kitlesel-Fonlama-Uygulamasi/commit/c6ded6eb2bfc95532155cdbc1ea5e4c4b854900e) operation, I made significant progress in the project. You can review the changes by reviewing the closed issues.

**Comment by erenburuk** [comment]
The latest frontend changes on the client side were pushed and [merged](https://github.com/CankayaUniversity/ceng-407-408-2023-2024-AGRICROWD-Tarimda-Kitlesel-Fonlama-Uygulamasi/commit/ff32ff4b0e154f7acf98270b8f8d0145b9e10a7a) successfully

**Comment by mustyilmaz** [comment]
Necessary requests after the last merge operations were fulfilled, errors were fixed and improvements were made.

**Comment by erenburuk** [comment]
Error messages refactored. AdminLogin, Home, AddProject, and more components UI are updated. Fixed the issue where the Navbar component was disrupting the page layout.

**Comment by erenburuk** [comment]
All UIs in the Admin section have been updated, Card component and Projects page have been added.

**Comment by adiltukenmez** [comment]
Added Reward Component and added the funcionality of creating the project in blockchain when admin approves the project.
