### ISSUE TITLE
 Preparation of Project Test Plan Document

### ISSUE THREAD

**Issue by mustyilmaz** [CankayaUniversity/ceng-407-408-2023-2024-AGRICROWD-Tarimda-Kitlesel-Fonlama-Uygulamasi#5]
- Check the sample document.
- Considering possible test scenarios according to determined use-cases.

**Comment by gklemr** [comment]
I uploaded a test plan document.

**Comment by gklemr** [comment]
You can add  it to wiki @erenburuk

**Comment by erenburuk** [comment]
Test Plan Document added to the wiki page.
