### ISSUE TITLE
Functionalization of the approved button of the pending projects component in the admin panel.

### ISSUE THREAD

**Issue by mustyilmaz** [CankayaUniversity/ceng-407-408-2023-2024-AGRICROWD-Tarimda-Kitlesel-Fonlama-Uygulamasi#56]
If the admin approves the relevant project:

- [x] The status of the project should be updated to "approved".
- [x] Transferring the project to the blockchain network by sending the necessary information to the smart contract.

**Comment by mustyilmaz** [comment]
When the Approve button is clicked, the status of the project is successfully approved.

**Comment by adiltukenmez** [comment]
When the Approve button is clicked, we take the necessary information and send it to the smart contract.
