### ISSUE TITLE
 Create a "Register" page for our project.

### ISSUE THREAD

**Issue by adiltukenmez** [CankayaUniversity/ceng-407-408-2023-2024-AGRICROWD-Tarimda-Kitlesel-Fonlama-Uygulamasi#6]
- Through this page, users can register to our website.
- The information obtained from this page should be saved/stored in the database.

**Comment by remzn** [comment]
I created the registration page by taking the name, surname, email and password from the user.

**Comment by mustyilmaz** [comment]
I also added: 
- Password matching
- Minimum password requirements (one uppercase letter, one lowercase letter etc.)
- reCAPTCHA verification to this panel. 

With these additions, we have completed the registration phase.
