### ISSUE TITLE
Create a "Login" page for our project. 

### ISSUE THREAD

**Issue by adiltukenmez** [CankayaUniversity/ceng-407-408-2023-2024-AGRICROWD-Tarimda-Kitlesel-Fonlama-Uygulamasi#7]
- Through this page, users can enter their information and log in to the site.
- The user information should be retrieved from the database.

**Comment by remzn** [comment]
I created a login page where users can enter their e-mail and password and continue to the system after the information they enter matches the information we received in the registration.

**Comment by mustyilmaz** [comment]
I also added reCAPTCHA verification. With these additions, we have completed the registration phase.
