### ISSUE TITLE
There are 2 "home" components for Admin Panel.

### ISSUE THREAD

**Issue by adiltukenmez** [CankayaUniversity/ceng-407-408-2023-2024-AGRICROWD-Tarimda-Kitlesel-Fonlama-Uygulamasi#76]
"Admin/Panel/" component has 2 home sub-components. One of them is "AdminHome" and the other one is "home". Since we don't use "AdminHome" sub-component, you can remove that component from the project.

**Comment by mustyilmaz** [comment]
Since the components are exactly the same, the ~/home folder and its sub-items have been deleted.
