### ISSUE TITLE
Development of the project "/" route.

### ISSUE THREAD

**Issue by mustyilmaz** [CankayaUniversity/ceng-407-408-2023-2024-AGRICROWD-Tarimda-Kitlesel-Fonlama-Uygulamasi#87]
- [x] Every time the page is refreshed, 3 or more random projects should be listed.
- [ ] The 'If you want to add a project' message and the 'Add Project' button underneath it should be retained in the component.
- [ ] The 3 projects that received the most investment should be listed under the "hot project or etc." heading in order of amount from highest to lowest.

Frontend: 
- [ ] It should be made more interesting with design. Design and placement of cards should be improved.

**Comment by gklemr** [comment]
Instead of 3 randomly, all projects are now shown in random order every time the page is refreshed. The filtering still works.

**Comment by gklemr** [comment]
I cant listed the top 3 funded project due to ethers error
