### ISSUE TITLE
Development of "My Investments" component for users.

### ISSUE THREAD

**Issue by mustyilmaz** [CankayaUniversity/ceng-407-408-2023-2024-AGRICROWD-Tarimda-Kitlesel-Fonlama-Uygulamasi#88]
- [ ] Users should be able to observe the projects in which they invested in this component here.
- [ ] If a profit distribution has been made, he/she should be able to observe the amount of profit distributed, the percentage and amount of his/her share.
- [ ] Finally, he/she should be able to withdraw his share to the wallet address where he/she made the investment.

**Comment by mustyilmaz** [comment]
I implemented the necessary routing mechanism and foldering process for "My Investments"

**Comment by adiltukenmez** [comment]
A simple My Inestments component is implemented and ready to be used.
