### ISSUE TITLE
Enhancement of features added to the UserNavbar component.

### ISSUE THREAD

**Issue by mustyilmaz** [CankayaUniversity/ceng-407-408-2023-2024-AGRICROWD-Tarimda-Kitlesel-Fonlama-Uygulamasi#94]
- [ ] The dropdown section that opens when relevant main buttons are clicked in the UserNavbar component overlaps with other buttons, necessitating the resolution of this issue and the implementation of necessary improvements.

**Comment by erenburuk** [comment]
Fixed the issue where the button expands when hovering in the "UserNavbar". 
There is no need to fix the overlap problem at the moment as it does not affect the appearance.
