### ISSUE TITLE
The project dashboard needs to be developed urgently.

### ISSUE THREAD

**Issue by mustyilmaz** [CankayaUniversity/ceng-407-408-2023-2024-AGRICROWD-Tarimda-Kitlesel-Fonlama-Uygulamasi#96]
I have prepared the template for the project dashboard. The following features are expected to be included in the dashboard of the respective project:

- [x]  When the project reaches its targeted amount, the entire balance should be successfully withdrawn to the relevant wallet address.
- [x] The project owner should be able to observe under the 'Transaction History' section, until the moment of their control, which wallet addresses have invested how much in the project. 
- [x] Once the project enters the profit stage, the project owner should send the profit amount to our platform or another smart contract, and profit distribution should automatically occur among the users who have invested in the project according to the amount they have invested.

**Comment by adiltukenmez** [comment]
Project Dashboard is developed and ready to be used.
